export class Constantes {

  static readonly CORS_SH = 'https://proxy.cors.sh/';
  static readonly CORS_SH_KEY = "live_f46a9eeffb5fcae750a356a53b2fb571016cebfba637410e864c6512fa625aa0";
  static readonly CLIENT_ID = "spn1fzis5flcrayf5ztt6g8uf49pnr";
  static readonly BEARER_FINAL = "Bearer n93jt392irs9htvwdxk77xtobjj4qm";

  static readonly STAR_GAMES = [
    "Alone in the Dark",
    "Apollo Justice: Ace Attorney Trilogy",
    "Death Stranding 2",
    "Destiny 2: The Final Shape",
    "Dragon's Dogma II",
    "Final Fantasy VII Rebirth",
    "Final Fantasy VII Remake & Rebirth: Twin Pack",
    "Like a Dragon: Infinite Wealth",
    "Metaphor: ReFantazio",
    "Persona 3 Reload",
    "Prince of Persia: The Lost Crown",
    "Rise of the Ronin",
    "Senua's Saga: Hellblade II",
    "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    "Star Wars: Outlaws",
    "Suicide Squad: Kill the Justice League",
    "Tekken 8",
    "Unicorn Overlord",
    "Warhammer 40,000: Space Marine II",
    "World of Warcraft: The War Within"];

  static readonly SEASON_GAMES = [
    "Diablo IV: Season of Blood",
    "Diablo IV: Season of the Malignant",
    "Destiny 2: Lightfall - Season of Defiance",
    "Destiny 2: Lightfall - Season of the Deep",
    "Destiny 2: Lightfall - Season of the Witch",
    "Destiny 2: Lightfall - Season of",
    "Exoprimal: Season 4",
    "Genshin Impact: Roses and Muskets",
    "Hearthstone: Showdown in the Badlands",
    "Warcraft Rumble: Season 1",
    "Warcraft Rumble: Season 2",
    "Warcraft Rumble: Season 3",
    "Warcraft Rumble: Season 4",
    "Halo Infinite: Season 7",
    "Halo Infinite: Season 8",
    "Honkai: Star Rail - Crown of the Mundane and Divine",
    "Mario Kart 8 Deluxe: Booster Course Pass - Wave 7",
    "Mario Kart 8 Deluxe: Booster Course Pass - Wave 8",
    "Overwatch 2: Season 7 - Rise of the Darkness",
    "Overwatch 2: Season 8 - Call of the Hunt",
    "Vampire Survivors: Emergency Meeting",
  ]

  static readonly PATCH_GAMES = [
    "Anno 1800: Eldritch Pack",
    "Age of Empires IV: The Sultans Ascend",
    "Fallout 76: Atlantic City",
    "Pokémon Violet: The Hidden Treasure of Area Zero - Part 1: The Teal Mask",
    "Pokémon Scarlet: The Hidden Treasure of Area Zero - Part 1: The Teal Mask",
    "Pokémon Violet + The Hidden Treasure of Area Zero",
    "Pokémon Scarlet + The Hidden Treasure of Area Zero",
    "Tales of Arise: Beyond the Dawn",
    "World of Warcraft: Dragonflight - Guardians of the Dream",
    "World of Warcraft Classic: Season of Discovery",
  ]

  static readonly COMPANIES = [
    "Activision",
    "Arc System Works",
    "Atlus",
    "AvantGarden Games",
    "Bandai Namco Studios",
    "Bethesda Game Studios",
    "Bethesda Softworks",
    "Blaze Entertainment",
    "Blizzard Entertainment",
    "Bungie",
    "Capcom",
    "Capcom Co., LTD.",
    "CD Projekt Red",
    "Cognosphere",
    "CREATIVE ASSEMBLY",
    "Croteam",
    "Chucklefish Games",
    "Digital Extremes",
    "Fast Travel Games",
    "Fntastic",
    "Guerrilla Games",
    "GSC Game World",
    "Electronic Arts",
    "EA Sports",
    "HEXWORKS",
    "Hoyoverse",
    "Innersloth",
    "Insomniac Games",
    "Massive Entertainment",
    "Microids",
    "Neos Corporation",
    "Nippon Ichi Software",
    "Nintendo",
    "Nuclear Tales",
    "Owlcat Games",
    "Poncle",
    "Relic Entertainment",
    "Saber Interactive",
    "Sega",
    "Sony Interactive Entertainment",
    "Squanch Games",
    "Square Enix",
    "Studio Wildcard",
    "Studio Zero",
    "Team NINJA",
    "Tequila Works",
    "THQ Nordic",
    "Too Kyo Games",
    "Ubisoft Entertainment",
    "Ubisoft Montpellier",
    "Ubisoft Singapore",
    "WB Games",
    "Xbox Game Studios"
  ]

  static readonly MONTHS_YEAR = [
    { opcion: 'Enero', valor: 1, append: 'ENE' },
    { opcion: 'Febrero', valor: 2, append: 'FEB' },
    { opcion: 'Marzo', valor: 3, append: 'MAR' },
    { opcion: 'Abril', valor: 4, append: 'ABR' },
    { opcion: 'Mayo', valor: 5, append: 'MAY' },
    { opcion: 'Junio', valor: 6, append: 'JUN' },
    { opcion: 'Julio', valor: 7, append: 'JUL' },
    { opcion: 'Agosto', valor: 8, append: 'AGO' },
    { opcion: 'Septiembre', valor: 9, append: 'SEP' },
    { opcion: 'Octubre', valor: 10, append: 'OCT' },
    { opcion: 'Noviembre', valor: 11, append: 'NOV' },
    { opcion: 'Diciembre', valor: 12, append: 'DIC' }
  ]
}